CREATE TABLE callgroup ( id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT );
CREATE TABLE grouporder ( id INTEGER PRIMARY KEY AUTOINCREMENT, groupid INT, userid INT );
CREATE TABLE log ( id INTEGER PRIMARY KEY AUTOINCREMENT, entrydate DATETIME, entryip TEXT, entrylog TEXT );
CREATE TABLE user ( id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, mobilenum TEXT );
