CREATE TABLE callgroup ( id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT );
CREATE TABLE grouporder ( id INTEGER PRIMARY KEY AUTOINCREMENT, groupid INT, userid INT );
CREATE TABLE log ( id INTEGER PRIMARY KEY AUTOINCREMENT, entrydate DATETIME, entryip TEXT, entrylog TEXT );
CREATE TABLE smsnotify ( id INTEGER PRIMARY KEY AUTOINCREMENT, userid INT, groupid INT, typeid INT );
CREATE TABLE user ( id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, mobilenum TEXT );
CREATE TABLE log404 ( id INTEGER PRIMARY KEY AUTOINCREMENT, entrydate DATETIME, entryip TEXT, url TEXT );
